### ISSUE TITLE
Pass the service container into the GRPC initializer func

### ISSUE THREAD

**Issue by aphistic** [efritz/nacelle#12]
Would it be possible to add the service container as a parameter on GRPCServerInitializerFunc (https://github.com/efritz/nacelle/blob/master/process/grpc.go#L29) ?  This would allow using injected services on api server implementations without needing to pass it in as a parameter to whatever is constructing that service.

**Comment by efritz** [comment]
You can already request it as a service in initializer struct:

https://github.com/efritz/nacelle/blob/master/process/grpc.go#L62

**Comment by efritz** [comment]
Does that work?

**Comment by aphistic** [comment]
Oh, I missed that.  I think it will, I'll have to check tomorrow.

**Comment by efritz** [comment]
This will do what you want as long as you have a GRPCServerInitializer and not a GRPCServerInitializerFunc. You can inject the container plus whatever services you want.

If I'm mistaken re-open.
