### ISSUE TITLE
Allow custom config structs for services such as GRPC and HTTP

### ISSUE THREAD

**Issue by aphistic** [efritz/nacelle#13]
I'd like to change the default GRPC port for a project I'm working on but it looks like the grpc code expects a `*process.GRPCConfig` explicitly.  An idea I have for supporting this would be to have a `GRPCConfig` interface instead that you would cast to that implements required fields as functions, such as `GRPCPort() int`.  I could then have a struct in my own package implement that with a different default port.

**Comment by efritz** [comment]
I've added the following things to create a new dynamic config struct from an existing one while changing the struct tags. This will also allow us to register configs for two instances of a process (two GRPC servers) which we couldn't do before. This ticket pushed me to a solution for that.

https://godoc.org/github.com/efritz/nacelle#ApplyTagModifiers
https://godoc.org/github.com/efritz/nacelle#EnvTagPrefixer
https://godoc.org/github.com/efritz/nacelle#DefaultTagSetter

The preferred method for loading configs is now (although backwards compat is maintained). 

https://github.com/efritz/nacelle/blob/master/process/grpc.go#L48

If configs are loaded this way, then you can register a config in your startup config map like

```
// ...
WhateverConfigToken: MustApplyTagModifiers(&WhateverConfig{}, NewDefaultTagSetter("port", 2345),
// ...
```

Let me know if this works for you.

**Comment by aphistic** [comment]
Awesome! I'm glad to hear about the support for two GRPC servers, I think I'm going to need that this week sometime.  I'll give the custom port number a try tomorrow night when I work on papertrail again.
