### ISSUE TITLE
Allow loading configs from files

### ISSUE THREAD

**Issue by aphistic** [efritz/nacelle#28]
In addition to loading configs from the environment it can be handy to load configs from files as well, especially with something like Kubernetes making it easy to map a config to a file.  I was looking at the source last night and I had a few ideas on how to implement it.  I saw there are some changes in the config branch that I haven't had a chance to look at yet so this might be wrong given those changes.

I would be able to implement this feature if you're ok with my proposal in general:

A new bootstrap option would be created called something like WithConfigLoader or something like that which would allow you to pass in a Config to use while bootstrapping.  In addition to this, three new Config types would be created: DefaultConfig which would just load the default values into the config struct, FileConfig which would handle loading configs from files and (I don't know a good name for this atm) PrioritizedConfig that would take an array of Configs and would attempt to load configs in the order they're passed in to the constructor, giving lowest priority to the first one on down.  This would allow something like first loading defaults, then loading FileConfig, finally loading EnvConfig so files override defaults and env overrides files.

FileConfig would work by having a few options that can be passed in to the constructor.  The first being just a ConfigFilePath(path string) that would load the config from a specific path and not try anything else fancy.  Next would be a ConfigFileName(name string) that would take just the base of a config name, such as `config`. Last would be a ConfigFileDirectory(path string) that would take a "search directory" where FileConfig would look for config files. ConfigFileDirectory could be provided multiple times to include multiple search paths and would search in the order the options are provided.

FileConfig would initially support loading configs from json, yaml and toml files. It would use the ConfigFileName as the root of the filename, ConfigFileDirectory as the directory to search in and one of the standard file extensions for the various supported file types to construct a path. For example if `ConfigFileName("config")` and `ConfigFileDirectory("/etc/")` were passed in, FileConfig would try to find `/etc/config.json`, `/etc/config.yaml`, `/etc/config.yml` and so on.  If it finds a file match it will load that file and prepare to populate the config struct with the values.

As far as loading FileConfig values into a config struct, I'm planning on using the struct tag `file` to contain a dot-delimited path to the value in a config file.  For example, if the `file` tag value is `"foo.bar"`, the value would attempt to be loaded from the `bar` property of the `foo` object and on down the line.  If a provided path doesn't exist in the config it will be ignored but if the path does exist and the types don't match it will be considered an error.

I think I covered all my thoughts on this, let me know what you think!

**Comment by efritz** [comment]
There's now a Sourcer object that takes a config variable name (the value of the env tag) and loads the value from a source. The env sourcer basically calls os.Getenv on VAR and PREFIX_VAR and returns one if it finds it.

You should be able to easily make a JSONFileSourcer or an INIFileSourcer, parse it on startup, then give back values from the parsed map as the config object requests them. Not sure what the format would look like for volume-mounted config maps in k8s, but I think Mitel could also use this option. A way to configure the sourcer already exists in the new config source branch that defaults to an env sourcer.

You may also want to make a MultiSourcer that takes in a list of other sourcers so we can do what you suggested about priorities. I think that would be a good solution.

The changes in that branch should get you 90% of the way there. Let me know if you have any questions.

**Comment by efritz** [comment]
Do you want to throw together some alternate sourcers and PR to that branch?

**Comment by aphistic** [comment]
Would you want a Sourcer for each file type or just a FileSourcer that can determine what it is based on the file extension (with the option of hinting at what it is in a config)?

**Comment by efritz** [comment]
FileSourcer might be cool with a FileLoader dependency. Then you could have orthogonal settings for each one (file sourcer may, for example, want to pull from one file or a directory).

**Comment by aphistic** [comment]
Ok, I'll take a crack at it and we can talk about it in the PR

**Comment by efritz** [comment]
Ok, added a more complete draft in the config-sources branch. Now we have:

- load from map[string]interface{}
- load from JSON file
- load from YAML file
- load from TOML file
- load from multiple sourcers (in registered order)
- read from a configmap directory

Right now I plan to keep the env tag as-is so the only behavioral change to the entire package is the addition of a source. This may require that you tag things like `env:"foo.bar.baz"` for configmap mounts, which will load the content from the mounted "foo.bar.baz" file and try to use it as a raw string or parse it as a JSON value.

I'm against the idea of adding additional struct tags that will behave differently across sources. Right now, env, default, required, and mask work the same regardless of sources. I think this is the correct design. Maybe the env tag name could be changed as we're not strictly pulling from the environment anymore, but I don't think that's a huge issue (we could also make that particular tag configurable at boot).

Could you actually try out the configmap loader to see if this will work for your purposes tomorrow? I'm not 100% sure what the config map volume looks like and don't have a k8s cluster set up at home. If there's something that doesn't quite work could you add some more tests?

**Comment by aphistic** [comment]
Hey, I agree that changing behavior of the existing tags is a bad idea (as is overloading the struct tags) but I think I might have explained what I was thinking wrong.  I was thinking of having a new struct tag `file` that would specify where in a loaded file the value would come from, not which file it would be loaded from.

For example, if you have the struct:
```
type Config struct {
    SomeString string `env:"SOMESTRING" file:"some.string" default:"my_default"`
    SomeInt int `env:"SOMEINT" file:"some.int" default:"1234"`
}
```

It would load the value of SomeString from the environment at PREFIX_SOMESTRING but it would load it from a file with the contents `{"some":{"string": "foo","int":4321}}` (for a JSON file). The idea with the ConfigFileName() and ConfigFileDirectory() was that the file loader would use that to load a single config file and then multiple config values would be loaded from within there, not that there are multiple files loaded with a single config value for each of them.  I don't think there needs to be a separate configmap loader, just a "directory" loader.  The idea came from how [sp13/viper](https://github.com/spf13/viper) handles reading config files.

**Comment by efritz** [comment]
That makes more sense. If you have a MWE of a app manifest/config map that mounts in a volume could you show me what the mounted volume actually looks like? I've read conflicting things.

I'd prefer the implementation to be tweaked a bit so that files are handled transparently:

 ```
type Config struct {
    SomeString string `env:"STRING" context:"some" default:"my_default"`
    SomeInt int `env:"INT" context:"some" default:"1234"`
}
```

Then this will work for the file with context you describe as well as loading directly from the environment with `export SOME='{"string": "foo","int":4321}'`. This will also keep backwards compatibility with existing applications.

What do you think about that? Then all the changes (besides replacing the configmap sourcer with a directory sourcer) are in the config struct and apply to all sourcers equally.

**Comment by efritz** [comment]
Let me try the context thing real quick.

**Comment by efritz** [comment]
Ok what of you think of this right now? See [test](https://github.com/efritz/nacelle/blob/c19877ba5804a5e63254ff5e03bdfb5d1a8c71c6/config/config_test.go#L41) and [config object](https://github.com/efritz/nacelle/blob/c19877ba5804a5e63254ff5e03bdfb5d1a8c71c6/config/mock_objects_test.go#L15).

Let me know if this is a good direction for you.

**Comment by aphistic** [comment]
I think I see what you're going for but I'm wondering why you don't want to have a specific tag per loader? If you have a tag that's specific to a type of loader it allows more flexibility in how you name/access something.  I think that trying to make something that's trying to reuse concepts for all cases is either going to be confusing to use or won't allow projects to implement things the way they want. I wouldn't have a problem with ENV being the only way things can be loaded by default and if you want things to be loaded from a file you have to set some preferred values in the bootstrap.

As far as the app manifest/config map it would be something like this:

For a yaml config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: my-app
data:
  config.yml: |
    foo:
      bar: 1
      baz: "qux"
    blah: false
```

For the same thing as a json config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: my-app
data:
  config.yml: |
    {
        "foo": {
            "bar": 1,
            "baz": "qux"
        },
        "blah": false
    }
```
Then the pod manifest could be something like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  namespace: my-app
spec:
  containers:
    - name: app
      image: my-app:latest
      volumeMounts:
        - mountPath: /app/config
          name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: my-app-config
```

In the case of the yaml file example this would create the file `/app/config/config.yml` with the contents:
```yaml
foo:
  bar: 1
  baz: "qux"
blah: false
```
With the json file example it would be similar except with the json file contents in the file `/app/config/config.json`.

Was that what you were wondering about wrt configmaps and app manifests?

**Comment by aphistic** [comment]
I just thought of more stuff...

In the above example I think the config struct would look like:
```go
type Config struct {
    Bar int `env:"bar" context:"foo"`
    Baz string `env:"baz" context:foo"`
    Blah string `env:"blah"`
}
```

I would prefer something like:
```go
type Config struct {
    Bar int `env:"foo_bar" file:"foo.bar"`
    Baz string `env:"foo_baz" file:"foo.bar"`
    Blah string `env:"blah" file:"blah"`
}
```
I feel like it's more explicit this way and it's easier for someone who's unfamiliar with the code to grok where the values come from in different cases.

**Comment by efritz** [comment]
I’m very hesitant to introduce source-specific flags because when you
aren’t locked in to reading from a specific source outside of your main
function. I think what is in that branch now is flexible enough for what
you want (as I understand it) and works pretty well with all sources so
far. If you add tags that work only in specific cases you changing not only
the source but also the struct population behavior in non obvious ways.

I could otherwise be convinced with a PR to that branch. Maybe I’m not
seeing some benefit I might see with a sample implementation or full use
case.

**Comment by efritz** [comment]
From your last comment I see a bit more clearly now. This assumes that: (1) loaders know what tags they want to read, (2) they only read a single "source" tag (env or file), and (3) they don't read both tags in a strange way, then we can do the following:

- revert the context stuff
- find a way to have the sourcer communicate what tags should be read for each source (this is trickier for multi-sourcer which may need to ask for multiple tags)
- take the first valid value that's found and try to coerce it into the correct type for the struct

Does that sound ok? If so, could you make a PR to the branch if you have time?

**Comment by aphistic** [comment]
I think those 3 assumptions you listed are some that I was operating under. I haven't had a chance to look through the loader/sourcer code yet because I've been busier this weekend than I anticipated but if you don't mind I would like to take a crack at what I was thinking in that PR.  If it's not something that works we can just throw it out, np.  I do think it might be the best way to explain what I'm thinking though and help me understand how the code works now.

**Comment by efritz** [comment]
Awesome. Fork from the branch I started because there's some additional refactoring there.

**Comment by aphistic** [comment]
I just looked through the code for the config branch and it looks like it'll work for me! I had a couple questions on the code but nothing big.

In the multi sourcer you have it taking the first vale as it's iterating. Would it make more sense to have each progressive sourcer overwrite the previous one? I think it would make the code cleaner because then you wouldn't need to check if the value was set already, you could just overwrite the value until you get to the end. In my head having the higher index sourcer overwrite the lower ones makes sense. What do you think?

I think I understand the way you have the file sourcers working. If you want multiple files to be read (default, config, override for example) you would have 3 file sourcers in the mult sourcer? What if you wanted to handle `.yaml` and `.yml`? Would that double the number you have in the list?

**Comment by efritz** [comment]
> In the multi sourcer you have it taking the first value as it's iterating. Would it make more sense to have each progressive sourcer overwrite the previous one? 

It early-returns on the first one found (not that it will necessarily coerce to the correct type, only that there exists the valid path in that source). Are you suggesting that these values merge multiple sources, or that you just take the last one (so that the sourcer list is low->high priority)?

> I think I understand the way you have the file sourcers working. If you want multiple files to be read (default, config, override for example) you would have 3 file sourcers in the mult sourcer? What if you wanted to handle .yaml and .yml? Would that double the number you have in the list?

Right now there's only a file sourcer that takes a direct path, not a directory or anything. There's also no sourcer that silently exits on a missing file, so you must **explicitly** know the file path (and that it exists).

Both of these things can change. Could you lay out your ideas or how you would like to deal with files (a directory sourcer, or possible file list/glob paths)?

**Comment by aphistic** [comment]
> It early-returns on the first one found (not that it will necessarily coerce to the correct type, only that there exists the valid path in that source). Are you suggesting that these values merge multiple sources, or that you just take the last one (so that the sourcer list is low->high priority)?

I was thinking it would take the last one.  This would allow you to have a multi sourcer that would do something like: file (one or more), env. This would allow files to override each other and then have the environment override that.

> Right now there's only a file sourcer that takes a direct path, not a directory or anything. There's also no sourcer that silently exits on a missing file, so you must **explicitly** know the file path (and that it exists).
> 
> Both of these things can change. Could you lay out your ideas or how you would like to deal with files (a directory sourcer, or possible file list/glob paths)?

I wrote out the previous part without remembering this part.  So having multiple files wouldn't work in the example i put above.  I'll put together some thoughts on a DirectorySourcer tonight. My keyboard is being a turd and I can't type long thoughts on it due to missed keystrokes, and duplicated keystrokes everywhere. =/

**Comment by efritz** [comment]
> This would allow you to have a multi sourcer that would do something like: file (one or more), env. 

You can do that just by putting env first and listing your files in priority order.

Will wait for your thoughts on DirectorySourcer.

**Comment by aphistic** [comment]
For the MultiSourcer I just thought it felt better for the order to be lowest to highest priority but I'm not super stuck on either option.

For the DirectorySourcer, I guess what are your ideas for a DirectorySourcer? I think I see it as a way to load a single file from a directory (without recursion) with one or more base names in order of priority which would then have standard file extensions added to it to find a file. Maybe something like this:

```go
sourcer := NewDirectorySourcer(
    "/etc/myapp", // Directory to search in
    []string{"config", "myapp"}, // Base filenames
)
```

This would create a sourcer that would try to find the files:
* /etc/myapp/config.json
* /etc/myapp/config.yml
* /etc/myapp/config.yaml
* /etc/myapp/config.toml
* /etc/myapp/myapp.json
* /etc/myapp/myapp.yml
* /etc/myapp/myapp.yaml
* /etc/myapp/myapp.toml

Once it found one of them it would load the file with the associated file type sourcer and would be treated as a FileSourcer after that. I don't know if I like the idea of multiple bases or if it's something that needs to exist but it might give more flexibility to people who want it?

This is similar to how viper and the nodejs "config" packages work with slightly less features.  In the case of nodejs the files are named based on the environment and/or host and I'm not sure it should go that far (take a look at [this](https://github.com/lorenwest/node-config/wiki/Configuration-Files) for more info on how that works).

I'm pretty open on the DirectorySourcer and I'm actually OK with how the file sourcers work atm but I'm trying to think of ways to make the config accessible and familiar (and less friction) to people who are coming from other options.

**Comment by efritz** [comment]
Ok I've updated a few things. Priority order for MultiSourcer has been reversed. There is now only one FileSourcer which takes a parser function as an optional second argument. If the parser is not supplied one will be chosen based on extension. The file MUST exist for the file parser.

I'm not sold on the directory sourcer, though. At least not that API. What's the use case of having such a restrictive input (no recursive search) that only cycles through extensions? I think possible just to have something like a OptionalFileSourcer that just no-ops when it can't open the file. Then you could just put a bunch of those in a MultiSourcer.

Thoughts on that?

**Comment by aphistic** [comment]
I like that idea!

**Comment by efritz** [comment]
Done! Anything else you want?

**Comment by aphistic** [comment]
I think that covers everything I was thinking about, I'd have to implement something with it to see if there's anything else. Thanks for working on that so quickly. :)
