### ISSUE TITLE
Allow changing the name of config fields

### ISSUE THREAD

**Issue by aphistic** [efritz/nacelle#3]
Our logging system uses the convention 'foo_bar' for naming attributes logged with log messages but currently the nacelle logs use the 'FooBar' convention (just the name of the struct property).  If there were a struct tag to give the name to use for the attr it would allow people to control the names themselves.  One issue I can see, though, is structs like the log config that users don't have access to won't be able to use this feature.  I'm not sure how (or if) you want to solve that issue.

**Comment by efritz** [comment]
Should be covered by 3b0a42b7003920038779363c799c9c7b32fe52df.
