### ISSUE TITLE
Allow configuring the listen address for base servers

### ISSUE THREAD

**Issue by aphistic** [efritz/nacelle#36]
I'm running into an issue on the firewall of my work-issued laptop where it pops up a firewall "allow/deny" notification every time I run a nacelle service locally.  It sounds like it's because the base http server (looks like grpc as well) is configured to listen on `0.0.0.0`. I'd like to be able to specify an ip (or even empty) for local development to avoid this annoyance. I think keeping a default value of `0.0.0.0` would still make sense, though.

**Comment by efritz** [comment]
Could you check if #37 does what you need?

**Comment by aphistic** [comment]
Yeah, I think it does. Thanks!
